# Generated by Django 6.0.1 on 2026-03-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Admin"), (2, "User")],
                default=2,
                help_text="1=Admin, 2=User",
            ),
        ),
    ]
