# Generated by Django 6.0.1 on 2026-02-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_author_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[("text", "Text"), ("image", "Image"), ("video", "Video")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="Untitled Post", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="password123", max_length=255),
        ),
    ]
