# Generated by Django 6.0.1 on 2026-03-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_remove_like_unique_user_post_like_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[("text", "Text"), ("image", "Image"), ("video", "Video")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
