# Generated by Django 6.0.1 on 2026-03-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_post_metadata_post_post_type_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="privacy_level",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Private"), (2, "Public")],
                default=2,
                help_text="1=Private, 2=Public",
            ),
            preserve_default=False,
        ),
    ]
