"""
Django settings for connectly_project project.

This file configures core Django settings including:
- Installed applications (Django default apps, third-party apps, and custom apps)
- Middleware and templates
- Database configuration
- Authentication and authorization settings
- Password validation and hashing
- REST Framework settings for API authentication
- Static files and internationalization

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
from decouple import config  # Optional for secure secret management

# -------------------- BASE DIRECTORY -------------------- #
# Base directory of the project, used to construct absolute paths
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------- SECURITY -------------------- #
# Keep the secret key safe in production (use environment variables in prod)
SECRET_KEY = 'django-insecure-_=$!=b#@y63vw_*)z7dk644-84vh95o(+s$j4qpsf5udy=1vd4'

# Debug should be False in production
DEBUG = True

# Conditional security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True  # Redirect all HTTP requests to HTTPS
    SESSION_COOKIE_SECURE = True  # Ensure cookies are only sent over HTTPS
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # HTTP Strict Transport Security duration
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Hosts allowed to access this Django site
ALLOWED_HOSTS = []


# -------------------- APPLICATIONS -------------------- #
INSTALLED_APPS = [
    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth social accounts

    # Third-party apps
    'rest_framework',  # Django REST Framework
    'rest_framework.authtoken',  # Token-based auth
    'rest_framework_simplejwt',  # JWT authentication
    'django_extensions',  # Extra management commands

    # Allauth and Google OAuth integration
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # Custom project apps
    'connectly_project.posts',
    'connectly_project.authentication.apps.AuthenticationConfig',
]
# Sites framework configuration (required by allauth)
SITE_ID = 2 

# Custom user model
AUTH_USER_MODEL = 'authentication.CustomUser'

# -------------------- MIDDLEWARE -------------------- #
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware', # Enables allauth features
]

# -------------------- URL CONFIGURATION -------------------- #
ROOT_URLCONF = 'connectly_project.urls'

WSGI_APPLICATION = 'connectly_project.wsgi.application'


# -------------------- DATABASE -------------------- #
# SQLite is used for development; switch to PostgreSQL or MySQL in production
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# -------------------- PASSWORD VALIDATION -------------------- #
# Enforce strong passwords for users
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password hashing algorithms, ordered by preference
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]


# -------------------- INTERNATIONALIZATION -------------------- #
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# -------------------- STATIC FILES -------------------- #
STATIC_URL = 'static/'


# -------------------- REST FRAMEWORK -------------------- #
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# -------------------- TEMPLATES -------------------- #
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Add custom template directories here
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# -------------------- AUTHENTICATION -------------------- #
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',   # Default Django authentication
    'allauth.account.auth_backends.AuthenticationBackend',   # Enables social login
]

# Social login configuration
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# Redirect URLs after login/logout
LOGIN_REDIRECT_URL = '/api/feed/'
LOGOUT_REDIRECT_URL = '/'